using System;
using System.Diagnostics;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Security;
using System.Security.Permissions;
using Fusion;
using Unity.Burst;

[assembly: AssemblyVersion("0.0.0.0")]
[assembly: NetworkAssemblyWeaved]
[assembly: BurstCompiler.StaticTypeReinitAttribute(typeof(Bindings.Vec3Functions.New_00003B58$BurstDirectCall))]
[assembly: BurstCompiler.StaticTypeReinitAttribute(typeof(Bindings.Vec3Functions.Add_00003B59$BurstDirectCall))]
[assembly: BurstCompiler.StaticTypeReinitAttribute(typeof(Bindings.Vec3Functions.Sub_00003B5A$BurstDirectCall))]
[assembly: BurstCompiler.StaticTypeReinitAttribute(typeof(Bindings.Vec3Functions.Mul_00003B5B$BurstDirectCall))]
[assembly: BurstCompiler.StaticTypeReinitAttribute(typeof(Bindings.Vec3Functions.Div_00003B5C$BurstDirectCall))]
[assembly: BurstCompiler.StaticTypeReinitAttribute(typeof(Bindings.Vec3Functions.Unm_00003B5D$BurstDirectCall))]
[assembly: BurstCompiler.StaticTypeReinitAttribute(typeof(Bindings.Vec3Functions.Eq_00003B5E$BurstDirectCall))]
[assembly: BurstCompiler.StaticTypeReinitAttribute(typeof(Bindings.Vec3Functions.Dot_00003B60$BurstDirectCall))]
[assembly: BurstCompiler.StaticTypeReinitAttribute(typeof(Bindings.Vec3Functions.Cross_00003B61$BurstDirectCall))]
[assembly: BurstCompiler.StaticTypeReinitAttribute(typeof(Bindings.Vec3Functions.Project_00003B62$BurstDirectCall))]
[assembly: BurstCompiler.StaticTypeReinitAttribute(typeof(Bindings.Vec3Functions.Length_00003B63$BurstDirectCall))]
[assembly: BurstCompiler.StaticTypeReinitAttribute(typeof(Bindings.Vec3Functions.Normalize_00003B64$BurstDirectCall))]
[assembly: BurstCompiler.StaticTypeReinitAttribute(typeof(Bindings.Vec3Functions.SafeNormal_00003B65$BurstDirectCall))]
[assembly: BurstCompiler.StaticTypeReinitAttribute(typeof(Bindings.Vec3Functions.Distance_00003B66$BurstDirectCall))]
[assembly: BurstCompiler.StaticTypeReinitAttribute(typeof(Bindings.Vec3Functions.Lerp_00003B67$BurstDirectCall))]
[assembly: BurstCompiler.StaticTypeReinitAttribute(typeof(Bindings.Vec3Functions.Rotate_00003B68$BurstDirectCall))]
[assembly: BurstCompiler.StaticTypeReinitAttribute(typeof(Bindings.Vec3Functions.ZeroVector_00003B69$BurstDirectCall))]
[assembly: BurstCompiler.StaticTypeReinitAttribute(typeof(Bindings.Vec3Functions.OneVector_00003B6A$BurstDirectCall))]
[assembly: BurstCompiler.StaticTypeReinitAttribute(typeof(Bindings.Vec3Functions.NearlyEqual_00003B6B$BurstDirectCall))]
[assembly: BurstCompiler.StaticTypeReinitAttribute(typeof(Bindings.QuatFunctions.New_00003B6C$BurstDirectCall))]
[assembly: BurstCompiler.StaticTypeReinitAttribute(typeof(Bindings.QuatFunctions.Mul_00003B6D$BurstDirectCall))]
[assembly: BurstCompiler.StaticTypeReinitAttribute(typeof(Bindings.QuatFunctions.Eq_00003B6E$BurstDirectCall))]
[assembly: BurstCompiler.StaticTypeReinitAttribute(typeof(Bindings.QuatFunctions.FromEuler_00003B70$BurstDirectCall))]
[assembly: BurstCompiler.StaticTypeReinitAttribute(typeof(Bindings.QuatFunctions.FromDirection_00003B71$BurstDirectCall))]
[assembly: BurstCompiler.StaticTypeReinitAttribute(typeof(Bindings.QuatFunctions.GetUpVector_00003B72$BurstDirectCall))]
[assembly: BurstCompiler.StaticTypeReinitAttribute(typeof(Bindings.QuatFunctions.Euler_00003B73$BurstDirectCall))]
[assembly: BurstCompiler.StaticTypeReinitAttribute(typeof(BurstClassInfo.Index_00003B80$BurstDirectCall))]
[assembly: BurstCompiler.StaticTypeReinitAttribute(typeof(BurstClassInfo.NewIndex_00003B81$BurstDirectCall))]
[assembly: BurstCompiler.StaticTypeReinitAttribute(typeof(BurstClassInfo.NameCall_00003B82$BurstDirectCall))]
[assembly: SecurityPermission(SecurityAction.RequestMinimum, SkipVerification = true)]
