using System;

// Token: 0x02000235 RID: 565
public static class UberShaderKeywords
{
	// Token: 0x040010CB RID: 4299
	public const string STEREO_INSTANCING_ON = "STEREO_INSTANCING_ON";

	// Token: 0x040010CC RID: 4300
	public const string UNITY_SINGLE_PASS_STEREO = "UNITY_SINGLE_PASS_STEREO";

	// Token: 0x040010CD RID: 4301
	public const string STEREO_MULTIVIEW_ON = "STEREO_MULTIVIEW_ON";

	// Token: 0x040010CE RID: 4302
	public const string STEREO_CUBEMAP_RENDER_ON = "STEREO_CUBEMAP_RENDER_ON";

	// Token: 0x040010CF RID: 4303
	public const string _GLOBAL_ZONE_LIQUID_TYPE__WATER = "_GLOBAL_ZONE_LIQUID_TYPE__WATER";

	// Token: 0x040010D0 RID: 4304
	public const string _GLOBAL_ZONE_LIQUID_TYPE__LAVA = "_GLOBAL_ZONE_LIQUID_TYPE__LAVA";

	// Token: 0x040010D1 RID: 4305
	public const string _ZONE_LIQUID_SHAPE__CYLINDER = "_ZONE_LIQUID_SHAPE__CYLINDER";

	// Token: 0x040010D2 RID: 4306
	public const string _USE_TEXTURE = "_USE_TEXTURE";

	// Token: 0x040010D3 RID: 4307
	public const string USE_TEXTURE__AS_MASK = "USE_TEXTURE__AS_MASK";

	// Token: 0x040010D4 RID: 4308
	public const string _USE_WEATHER_MAP = "_USE_WEATHER_MAP";

	// Token: 0x040010D5 RID: 4309
	public const string _ALPHA_DETAIL_MAP = "_ALPHA_DETAIL_MAP";

	// Token: 0x040010D6 RID: 4310
	public const string _WATER_EFFECT = "_WATER_EFFECT";

	// Token: 0x040010D7 RID: 4311
	public const string _HEIGHT_BASED_WATER_EFFECT = "_HEIGHT_BASED_WATER_EFFECT";

	// Token: 0x040010D8 RID: 4312
	public const string _ALPHATEST_ON = "_ALPHATEST_ON";

	// Token: 0x040010D9 RID: 4313
	public const string _MAINTEX_ROTATE = "_MAINTEX_ROTATE";

	// Token: 0x040010DA RID: 4314
	public const string _UV_WAVE_WARP = "_UV_WAVE_WARP";

	// Token: 0x040010DB RID: 4315
	public const string _LIQUID_VOLUME = "_LIQUID_VOLUME";

	// Token: 0x040010DC RID: 4316
	public const string _LIQUID_CONTAINER = "_LIQUID_CONTAINER";

	// Token: 0x040010DD RID: 4317
	public const string _EMISSION = "_EMISSION";

	// Token: 0x040010DE RID: 4318
	public const string _EMISSION_USE_UV_WAVE_WARP = "_EMISSION_USE_UV_WAVE_WARP";

	// Token: 0x040010DF RID: 4319
	public const string _USE_DEFORM_MAP = "_USE_DEFORM_MAP";

	// Token: 0x040010E0 RID: 4320
	public const string _USE_DAY_NIGHT_LIGHTMAP = "_USE_DAY_NIGHT_LIGHTMAP";

	// Token: 0x040010E1 RID: 4321
	public const string _USE_TEX_ARRAY_ATLAS = "_USE_TEX_ARRAY_ATLAS";

	// Token: 0x040010E2 RID: 4322
	public const string _CRYSTAL_EFFECT = "_CRYSTAL_EFFECT";

	// Token: 0x040010E3 RID: 4323
	public const string _EYECOMP = "_EYECOMP";

	// Token: 0x040010E4 RID: 4324
	public const string _MOUTHCOMP = "_MOUTHCOMP";

	// Token: 0x040010E5 RID: 4325
	public const string _ALPHA_BLUE_LIVE_ON = "_ALPHA_BLUE_LIVE_ON";

	// Token: 0x040010E6 RID: 4326
	public const string _GRID_EFFECT = "_GRID_EFFECT";

	// Token: 0x040010E7 RID: 4327
	public const string _REFLECTIONS = "_REFLECTIONS";

	// Token: 0x040010E8 RID: 4328
	public const string _REFLECTIONS_BOX_PROJECT = "_REFLECTIONS_BOX_PROJECT";

	// Token: 0x040010E9 RID: 4329
	public const string _REFLECTIONS_USE_NORMAL_TEX = "_REFLECTIONS_USE_NORMAL_TEX";

	// Token: 0x040010EA RID: 4330
	public const string _VERTEX_ROTATE = "_VERTEX_ROTATE";

	// Token: 0x040010EB RID: 4331
	public const string _VERTEX_ANIM_FLAP = "_VERTEX_ANIM_FLAP";

	// Token: 0x040010EC RID: 4332
	public const string _VERTEX_ANIM_WAVE = "_VERTEX_ANIM_WAVE";

	// Token: 0x040010ED RID: 4333
	public const string _VERTEX_ANIM_WAVE_DEBUG = "_VERTEX_ANIM_WAVE_DEBUG";

	// Token: 0x040010EE RID: 4334
	public const string _VERTEX_LIGHTING = "_VERTEX_LIGHTING";

	// Token: 0x040010EF RID: 4335
	public const string _GRADIENT_MAP_ON = "_GRADIENT_MAP_ON";

	// Token: 0x040010F0 RID: 4336
	public const string _PARALLAX = "_PARALLAX";

	// Token: 0x040010F1 RID: 4337
	public const string _PARALLAX_AA = "_PARALLAX_AA";

	// Token: 0x040010F2 RID: 4338
	public const string _PARALLAX_PLANAR = "_PARALLAX_PLANAR";

	// Token: 0x040010F3 RID: 4339
	public const string _MASK_MAP_ON = "_MASK_MAP_ON";

	// Token: 0x040010F4 RID: 4340
	public const string _FX_LAVA_LAMP = "_FX_LAVA_LAMP";

	// Token: 0x040010F5 RID: 4341
	public const string _INNER_GLOW = "_INNER_GLOW";

	// Token: 0x040010F6 RID: 4342
	public const string _STEALTH_EFFECT = "_STEALTH_EFFECT";

	// Token: 0x040010F7 RID: 4343
	public const string _UV_SHIFT = "_UV_SHIFT";

	// Token: 0x040010F8 RID: 4344
	public const string _TEXEL_SNAP_UVS = "_TEXEL_SNAP_UVS";

	// Token: 0x040010F9 RID: 4345
	public const string _UNITY_EDIT_MODE = "_UNITY_EDIT_MODE";

	// Token: 0x040010FA RID: 4346
	public const string _GT_EDITOR_TIME = "_GT_EDITOR_TIME";

	// Token: 0x040010FB RID: 4347
	public const string _DEBUG_PAWN_DATA = "_DEBUG_PAWN_DATA";

	// Token: 0x040010FC RID: 4348
	public const string _COLOR_GRADE_PROTANOMALY = "_COLOR_GRADE_PROTANOMALY";

	// Token: 0x040010FD RID: 4349
	public const string _COLOR_GRADE_PROTANOPIA = "_COLOR_GRADE_PROTANOPIA";

	// Token: 0x040010FE RID: 4350
	public const string _COLOR_GRADE_DEUTERANOMALY = "_COLOR_GRADE_DEUTERANOMALY";

	// Token: 0x040010FF RID: 4351
	public const string _COLOR_GRADE_DEUTERANOPIA = "_COLOR_GRADE_DEUTERANOPIA";

	// Token: 0x04001100 RID: 4352
	public const string _COLOR_GRADE_TRITANOMALY = "_COLOR_GRADE_TRITANOMALY";

	// Token: 0x04001101 RID: 4353
	public const string _COLOR_GRADE_TRITANOPIA = "_COLOR_GRADE_TRITANOPIA";

	// Token: 0x04001102 RID: 4354
	public const string _COLOR_GRADE_ACHROMATOMALY = "_COLOR_GRADE_ACHROMATOMALY";

	// Token: 0x04001103 RID: 4355
	public const string _COLOR_GRADE_ACHROMATOPSIA = "_COLOR_GRADE_ACHROMATOPSIA";

	// Token: 0x04001104 RID: 4356
	public const string LIGHTMAP_ON = "LIGHTMAP_ON";

	// Token: 0x04001105 RID: 4357
	public const string DIRLIGHTMAP_COMBINED = "DIRLIGHTMAP_COMBINED";

	// Token: 0x04001106 RID: 4358
	public const string INSTANCING_ON = "INSTANCING_ON";

	// Token: 0x04001107 RID: 4359
	public static readonly string[] namesArray = new string[]
	{
		"STEREO_INSTANCING_ON",
		"UNITY_SINGLE_PASS_STEREO",
		"STEREO_MULTIVIEW_ON",
		"STEREO_CUBEMAP_RENDER_ON",
		"_GLOBAL_ZONE_LIQUID_TYPE__WATER",
		"_GLOBAL_ZONE_LIQUID_TYPE__LAVA",
		"_ZONE_LIQUID_SHAPE__CYLINDER",
		"_USE_TEXTURE",
		"USE_TEXTURE__AS_MASK",
		"_USE_WEATHER_MAP",
		"_ALPHA_DETAIL_MAP",
		"_WATER_EFFECT",
		"_HEIGHT_BASED_WATER_EFFECT",
		"_ALPHATEST_ON",
		"_MAINTEX_ROTATE",
		"_UV_WAVE_WARP",
		"_LIQUID_VOLUME",
		"_LIQUID_CONTAINER",
		"_EMISSION",
		"_EMISSION_USE_UV_WAVE_WARP",
		"_USE_DEFORM_MAP",
		"_USE_DAY_NIGHT_LIGHTMAP",
		"_USE_TEX_ARRAY_ATLAS",
		"_CRYSTAL_EFFECT",
		"_EYECOMP",
		"_MOUTHCOMP",
		"_ALPHA_BLUE_LIVE_ON",
		"_GRID_EFFECT",
		"_REFLECTIONS",
		"_REFLECTIONS_BOX_PROJECT",
		"_REFLECTIONS_USE_NORMAL_TEX",
		"_VERTEX_ROTATE",
		"_VERTEX_ANIM_FLAP",
		"_VERTEX_ANIM_WAVE",
		"_VERTEX_ANIM_WAVE_DEBUG",
		"_VERTEX_LIGHTING",
		"_GRADIENT_MAP_ON",
		"_PARALLAX",
		"_PARALLAX_AA",
		"_PARALLAX_PLANAR",
		"_MASK_MAP_ON",
		"_FX_LAVA_LAMP",
		"_INNER_GLOW",
		"_STEALTH_EFFECT",
		"_UV_SHIFT",
		"_TEXEL_SNAP_UVS",
		"_UNITY_EDIT_MODE",
		"_GT_EDITOR_TIME",
		"_DEBUG_PAWN_DATA",
		"_COLOR_GRADE_PROTANOMALY",
		"_COLOR_GRADE_PROTANOPIA",
		"_COLOR_GRADE_DEUTERANOMALY",
		"_COLOR_GRADE_DEUTERANOPIA",
		"_COLOR_GRADE_TRITANOMALY",
		"_COLOR_GRADE_TRITANOPIA",
		"_COLOR_GRADE_ACHROMATOMALY",
		"_COLOR_GRADE_ACHROMATOPSIA",
		"LIGHTMAP_ON",
		"DIRLIGHTMAP_COMBINED",
		"INSTANCING_ON"
	};
}
